name: Build and Release DEB Package
on:
  push:
    tags:
      - 'v*.*.*' # Trigger on version tags like v1.0.0
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Build DEB package
        run: dpkg-deb --build .
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISHING_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
      - name: Upload DEB package to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISHING_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./icecast-mpv-sink.deb
          asset_name: icecast-mpv-sink-${GITHUB_REF_NAME#v}.deb
          asset_content_type: application/vnd.debian.binary-package
